name: CustomSkill
version: Umm...
api-version: 1.20
main: taewookim.CustomSkillPlugin

depend:
  - BattleSystem

permissions:
  skilluser.admin:
    default: op
    children:
      - skilluser.user
  skilluser.user:
    default: true

commands:
  skillmaker:
    permission: skilluser.admin
  skillitem:
    permission: skilluser.admin